ARG DEBIAN_FRONTEND=noninteractive
ARG BASE_DIST

FROM ${BASE_DIST}

ENV LANG C.UTF-8
ENV XDXCT_VISIBLE_DEVICES=all
ENV XDXCT_DRIVER_CAPABILITIES=graphics,compute,video

WORKDIR /tmp

COPY sources.list /etc/apt/

RUN apt-get update \
 && apt-get install -y --no-install-recommends vlc \
 && rm -rf /var/lib/apt/lists/*  

RUN sed -i 's/geteuid/getppid/' /usr/bin/vlc

ENTRYPOINT ["/bin/bash"]
