ARG DEBIAN_FRONTEND=noninteractive
ARG BASE_DIST

FROM ${BASE_DIST}

ENV LANG C.UTF-8
ENV XDG_RUNTIME_DIR /run/user/1000

WORKDIR /

#Dependencies for glvnd and Xcb.
RUN apt-get update && \
    apt-get install -y -qq --no-install-recommends \
      libglvnd0 \
      libgl1 \
      libglx0 \
      libegl1 \
      libgles2 \
      libxcb1-dev \
      vulkan-tools \
      libxcb-randr0-dev && \
    rm -rf /var/lib/apt/lists/*
  
COPY xdxgpu_icd.json /etc/vulkan/icd.d/
