ARG DEBIAN_FRONTEND=noninteractive
ARG BASE_DIST

FROM ${BASE_DIST}

ENV LANG C.UTF-8
ENV XDG_RUNTIME_DIR /var/tmp
ENV LIBVA_DRIVER_NAME xdxgpu

WORKDIR /tmp

RUN apt-get update \
 && apt-get install -y --no-install-recommends vlc dbus-x11 pulseaudio \
 && rm -rf /var/lib/apt/lists/*  

RUN sed -i 's/geteuid/getppid/' /usr/bin/vlc

RUN echo "pulseaudio --start 2>/dev/null" >> /root/.bashrc
ENTRYPOINT ["/bin/bash"]
