ARG DEBIAN_FRONTEND=noninteractive
ARG BASE_DIST

FROM ${BASE_DIST}

ENV LANG C.UTF-8
ENV XDXCT_VISIBLE_DEVICES=all
ENV XDXCT_DRIVER_CAPABILITIES=utility

WORKDIR /

RUN apt-get update \
  && apt-get install -y -qq --no-install-recommends \
    python3 \
    libpciaccess-dev \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "/bin/bash" ]
