version: '2.3'
services:
  clinfo-demo:
    image:  hub.xdxct.com/xdxct-docker/xdxgpu/clinfo-opencl-sample:1.0.0-Demo-rc-1 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/xdxgpu/lib/x86_64-linux-gnu 
    command: bash
    stdin_open: true
    tty: true
