version: '3'
services:
  clinfo-demo:
    image: hub.xdxct.com/xdxct-docker/xdxgpu/clinfo-opencl-sample:1.0.0-Demo-rc-1 
    environment:
      - XDXCT_DRIVER_CAPABILITIES=graphics,compute
    volumes:
      - ${PWD}/10-xdxgpu.conf:/usr/share/X11/xorg.conf.d/10-xdxgpu.conf
      - /tmp/.X11-unix:/tmp/.X11-unix 
    stdin_open: true
    tty: true
