version: '3'
services:
  vlc-video-demo:
    image: hub.xdxct.com/xdxct-docker/xdxgpu/vlc-video-sample:latest
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/var/tmp
    volumes:
      - ${HOME}/media/:/tmp/content
      - /var/run/dbus:/var/run/dbus:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id
      - ${PWD}/10-xdxgpu.conf:/usr/share/X11/xorg.conf.d/10-xdxgpu.conf
      - /tmp/.X11-unix:/tmp/.X11-unix  
      - /data/video_new:/tmp/video:ro
    stdin_open: true
    tty: true
