ARG DEBIAN_FRONTEND=noninteractive
ARG BASE_DIST

FROM ${BASE_DIST}

ENV LANG C.UTF-8
ENV XDXCT_VISIBLE_DEVICES=all
ENV XDXCT_DRIVER_CAPABILITIES=graphics,compute

WORKDIR /

#Dependencies for glvnd and X11.
RUN apt-get update \
  && apt-get install -y -qq --no-install-recommends \
    vim \
    make \
    gdb \
    build-essential \
    opencl-headers \
    clinfo \
  && rm -rf /var/lib/apt/lists/*

# 设置 EntryPoint
ENTRYPOINT ["/bin/bash"]
